name: smart_inverter
description: A modern desktop application for monitoring and controlling PowMr / SmartESS solar inverters.
publish_to: 'none'
version: 1.2.2+13

# Repository and homepage
repository: https://github.com/yuraantonov11/siseli-app
homepage: https://github.com/yuraantonov11/siseli-app

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.4.0
  crypto: ^3.0.3
  encrypt: ^5.0.3
  system_tray: ^2.0.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  launch_at_startup: ^0.5.1 # Пакет для автозапуску з Windows

  intl: any
  fl_chart: ^1.2.0
  window_manager: ^0.5.1
  package_info_plus: ^9.0.1
  url_launcher: ^6.3.2
  http: ^1.2.1
  path_provider: ^2.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4 # Пакет для генерації іконок
  flutter_lints: ^6.0.0 # Пакет для перевірки коду
  msix: ^3.16.7
dependency_overrides:
  path_provider_android: 2.2.1
# Налаштування генератора іконок
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 256

msix_config:
  display_name: Smart Inverter
  publisher_display_name: Yura Antonov
  publisher: CN=A887A8A8-8888-8888-8888-888888888888
  identity_name: com.yuraantonov.smartinverter
  msix_version: 1.2.2.0
  logo_path: assets/app_icon.png
  capabilities: internetClient, privateNetworkClientServer
  install_certificate: false

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/